spring.application.name=demo
# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JDBC URL
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Disable Spring Security (optional, only for dev)
spring.security.enabled=false

logging.level.root:DEBUG




